#!/bin/bash
PWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
declare -a UNWANTED
TEMP="$HOME/.temp"

# Welcome Message
echo "Please mark the modules you dont want."
echo "To use a module hit ENTER."

for MODULE in $(ls $PWD)
do
	# Dont show following modules
	# add as needed
	case $MODULE in
		1start)
			continue
			;;
		2toc)
			continue
			;;
	esac

	# Get input
	# Go up 1 clear line
	echo $MODULE > $TEMP
	NAME=$(perl -pe "s/[0123456789]//g" "$TEMP")
	rm $TEMP
	read -p "$NAME: " BOO
	echo -ne "\e[1A\e[K" >&2
	
	# Replace line with choice
	case $BOO in
	"")
		echo -ne "$NAME: X" >&2
		;;
	*)
		UNWANTED+="$MODULE "
		echo -ne "$NAME: -" >&2
		;;
	esac
	echo


done

# Give $WANTED to script
for DIS in $UNWANTED; do
	mv $MODULES/$DIS $DISABLED/$DIS
done
