#!/bin/bash
SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TEMP="$HOME/.temp"

read -p "[ ] Name: " NAME
echo -ne "\e[A\e[K" >&2
echo -ne "[X] Name: $NAME" >&2
echo >&2

echo -e "# $NAME\r" >> $TEMP
