#!/bin/bash
SRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TEMP="$HOME/.temp"
EDITOR="$HOME/.editor"

# Cleaning up
if [ -f $EDITOR ]; then rm "$EDITOR"; fi

clear
echo "INSTALLATION"
echo "Redirecting..."
sleep 1
vim -o "$EDITOR"
clear

echo -e "## Installation\n$(cat "$EDITOR")\n" >> "$TEMP"
